name: Deploy to Hugging Face Spaces
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://hardik1247:${HF_TOKEN}@huggingface.co/spaces/hardik1247/Search_Engine_llm
          git push --force space main

